<?php
/**
 * Genesis Framework.
 *
 * WARNING: This file is part of the core Genesis Framework. DO NOT edit this file under any circumstances.
 * Please do all modifications in the form of a child theme.
 *
 * @package Genesis\Templates
 * @author  StudioPress
 * @license GPL-2.0+
 * @link    http://my.studiopress.com/themes/genesis/
 */

add_action( 'genesis_before_content', 'custom_content' );
function custom_content() {
	
	
	$heroShortcode = get_field("slider_shortcode");
	
	if($heroShortcode) {
		echo do_shortcode($heroShortcode);
	}
	
	
	echo '<div id="why-invest" class="news-container container">';
	
		echo '<h2>' . get_field("news_heading") . '</h2>';
		echo '<div class="row">';
	
		if( have_rows('news_item') ):
	
			$n = 0;
			while ( have_rows('news_item') ) : the_row();
		    
		    	if($n % 3 == 0) {
			    	//echo '<div class="row">';
		    	}
		    ?>	
		    
				<div class="col-md-4 col-sm-6">
					
					<div class="news-image" style="background-image: url(<?php the_sub_field('news_image'); ?>)"></div>
				
					<div class="news-item">
						<a href="<?php the_sub_field('news_link'); ?>">
					
						<h3><?php the_sub_field('news_title'); ?></h3>
						
						<?php the_sub_field('news_description'); ?>
						
						<div class="date-block"><?php the_sub_field('news_date'); ?></div>
						</a>
					</div>
					
				</div>				
				
			<?php
				
				if(($n + 1) % 3 == 0) {
			    	//echo '</div>';
		    	}
				 
			$n++;
			endwhile;
			
			// if the last counter is not divisible by three, there is a row left open
			if(($n + 1) % 3 != 0) {
		    	//echo '</div>';
	    	}
	    	
	    	//echo '</div>';
		endif;
	
	echo '</div>';
	echo '</div>';
	
	?>
	
	<div class="banner">
		<div class="banner-wrap">
			<div class="top-small-text"><?php the_field('banner_small_text'); ?></div>
			<div class="row">
				<div class="left">
					<div class="main-text"><?php the_field('banner_main_text'); ?></div>
				</div>
				<div class="right">
					<a href="<?php the_field('banner_button_link'); ?>" class="button-white"><?php the_field('banner_button_text'); ?></a>
				</div>
			</div>
		</div>
	</div>
		
		
	<div id="why-freeman" class="banner-block">
		
		<div class="banner-block-wrap">
			<h2><?php the_field('whyf_heading'); ?></h2>
			
			<div class="banner-cols">
			
				<?php 
				if( have_rows('whyf_info_sections') ):
					while ( have_rows('whyf_info_sections') ) : the_row();
				?>
					<div class="col-md-3 col-sm-6">
						
						<div class="num"><?php the_sub_field('whyf_infosec_number'); ?></div>
						<div class="title"><?php the_sub_field('whyf_infosec_title'); ?></div>
						<div class="description"><?php the_sub_field('whyf_infosec_description'); ?></div>
						
					</div>
				
				<?php endwhile; ?>	
				<?php endif; ?>
			</div>
			<div style="clear:both"></div>
			
			<div class="content-blurb">
				<?php the_field('whyf_content_blurb'); ?>
			</div>
			
			<div class="banner-block-middle">
				<div class="banner-block-left">
					
					<img src="<?php the_field('whyf_left_image'); ?>" />
					
				</div>
				<div class="banner-block-right">
					<h5><?php the_field('whyf_content_heading'); ?></h5>
					<div class="description"><?php the_field('whyf_content_description'); ?></div>
					<a href="<?php the_field('whyf_content_button_link'); ?>" class="button-white"><?php the_field('whyf_content_button_text'); ?></a>
				</div>
			</div>
			<div style="clear:both"></div>
			<div class="banner-block-middle-sub">
				<h5 style="display: none"><?php the_field('tp_heading'); ?></h5>
				
				<div>
					<div class="col-md-12">
						<img src="<?php the_field('tp_image'); ?>" />
					</div>
				</div>
				
				<!--
				<div class="mid-banner-cols">
				-->						
					<?php /*
					if( have_rows('tp_sections') ):
						while ( have_rows('tp_sections') ) : the_row();
					?>
					
						<div class="col-md-6">
							<h4><?php the_sub_field('tp_section_title'); ?></h4>
							<div>
								
								<div class="left">
									<div class="fa fa-briefcase"></div>
									<div class="plus-sign">	
										<?php the_sub_field('tp_section_num_investors'); ?>
									</div>
									<div class="item-label">INVESTORS</div>
								</div>
								<div class="right">
									<div class="fa fa-dollar"></div>
									<div class="million">
										<?php the_sub_field('tp_section_num_funds'); ?>
									</div>
									<div class="item-label">FUNDS <br>UNDER MANAGMENT</div>
								</div>
								
							</div>
					
						</div>
						
					<?php endwhile; ?>	
					<?php endif; */?>
				<!--</div>-->
				<div style="clear: both"></div>
			</div>			
		</div>
	</div>
	<div class="banner-block-bottom-color"></div>
	<div id="plan-your-future" class="banner-block banner-block-full-width" style="background-image: url(<?php the_field('pyf_background_img'); ?>); background-repeat: no-repeat; background-size: cover; background-position: center;">
		<div class="banner-block-wrap">
			<h2><?php the_field('pyf_heading'); ?></h2>
			
			<div class="banner-cols" style="padding-bottom: 190px;">
			
				<h5 style="text-align: center; color: #fff; padding-top: 65px; padding-bottom: 65px"><?php the_field('pyf_section_title'); ?></h5>
				<?php 
				if( have_rows('how_it_works') ):
					while ( have_rows('how_it_works') ) : the_row();
				?>
				
					<div class="col-md-3 col-sm-6">
						
						<div class="num orange"><?php the_sub_field('hiw_infosec_number'); ?></div>
						<div class="title"><?php the_sub_field('hiw_infosec_title'); ?></div>
						<div class="description"><?php the_sub_field('hiw_infosec_description'); ?></div>
						
					</div>
				
				<?php endwhile; ?>	
				<?php endif; ?>
				<div style="clear:both"></div>
			</div>
<!--
			<div class="banner banner-form">
				<div class="banner-wrap">
					<div class="top-small-text">Begin Your Wealth Building Strategy</div>
					<div class="row">
						<div class="left">
							<div class="main-text">
								I want to invest 
								<span>$25,000</span> for 
								<span>10+ years</span>
								
							</div>
						</div>
							
						<div class="right">
							<a href="#" class="button-white">GET STARTED</a>
						</div>
					</div>
				</div>
			</div>	-->
			
			<div class="banner banner-form">
				<div class="banner-wrap">
					<div class="top-small-text"><?php the_field('banner_two_small_text'); ?></div>
					<div class="row">
						<div class="left">
							<div class="main-text"><?php the_field('banner_two_main_text'); ?></div>
						</div>
						<div class="right">
							<a href="<?php the_field('banner_two_button_link'); ?>" class="button-white"><?php the_field('banner_two_button_text'); ?></a>
						</div>
					</div>
				</div>
			</div>
			
					
		</div>
	</div>	
	<div class="banner-block-bottom-color" style="background: #262626 !important; height: 168px; margin-bottom: -189px; top: -188px"></div>
	<div class="top-footer">
		<div class="container">
			<div class="row">
				<div class="col-md-4">
					<div class="footer-text">
					SIGN UP FOR FREE WEALTH BUILDING TIPS
					</div>
				</div>
				<div class="col-md-4">
					<!--
					<input type="text" placeholder="Enter Your Email" /><button type="submit" class="button button-default">Send</button>-->
					<?php 
						echo do_shortcode('[yikes-mailchimp form="1"]');
					?>
					
				</div>
				<div class="col-md-4">
					<div class="footer-text">
					LET'S BE FRIENDS <div class="social-icons"><a href="https://www.instagram.com/freemancapital/" target="_blank"><span class="fa fa-instagram"></span></a><a href="http://www.medium.com/freeman-capital" target="_blank"><span class="fa fa-medium"></span></a><a href="http://www.facebook.com/freemancapital" target="_blank"><span class="fa fa-facebook"></span></a></div>
					</div>
				</div>
			</div>
			<div class="row">
			<div class="col-md-12">
				<div style="font-weight: 700; letter-spacing: 0px; color: rgb(238, 238, 238); font-size: 14px; position: relative; top:25px ;font-family: Oxygen; text-align: center;">
				Investing involves substantial risk. Always consider a financial professional when investing. Past performance is not indicative of future returns. Forex trading involves significant risk of loss and is not suitable for all investors.
				</div>
			</div>
			</div>
		</div>
	</div>
		
		
	<?php
}


// Initialize genesis
genesis();

?>


<script type="text/javascript">
// init controller
var controller = new ScrollMagic.Controller();
// create a scene
new ScrollMagic.Scene({
//duration: 900,    // the scene should last for a scroll distance of 100px
offset: 70        // start this scene after scrolling for 50px
})
.setClassToggle(".site-header", 'solid') // pins the element for the the scene's duration
.addTo(controller); // assign the scene to the controller


jQuery(document).ready(function($) {
	
	// Smooth scrolling for all anchor URLs on the same page
	$('a[href*="#"]:not([href="#"])').click(function() {
	    if (location.pathname.replace(/^\//,'') === this.pathname.replace(/^\//,'') && location.hostname === this.hostname) {
			var target = $(this.hash);
			target = target.length ? target : $('[name=' + this.hash.slice(1) +']');
			if (target.length) {
				$('html, body').animate({
					scrollTop: target.offset().top - 70
				}, 700);
				
				return false;
			}
	    }
	});
	
});

</script>




<div id="signup-modal" class="modal fade signup-modal" tabindex="-1" role="dialog">
	<div class="modal-dialog modal-md" role="document">
		<div class="modal-content">
		    <div class="modal-header">
		    	<button type="button" class="close" data-dismiss="modal" aria-label="Close">
		    		<span aria-hidden="true">&times;</span>
				</button>
		  	</div>
		  	<div class="modal-body">
		    	<div class="row">
					<div class="col-md-12">
						<h2>SIGN UP FOR FREE WEALTH BUILDING TIPS</h2>
						<h2><?php echo $title; ?></h2>
					</div>
					<div class="col-md-12">
						<?php echo do_shortcode('[yikes-mailchimp form="1"]'); ?>
						<?php echo $content; ?>
					</div>
		      	</div>	
			</div>
		</div>
	</div>
</div>


<?php
$page_data = get_page_by_path('terms-of-use');

//store page title and content in variables
$title = $page_data->post_title; 
$content = apply_filters('the_content', $page_data->post_content);
?>
<div id="terms-modal" class="modal fade" tabindex="-1" role="dialog">
	<div class="modal-dialog modal-lg" role="document">
		<div class="modal-content">
		    <div class="modal-header">
		    	<button type="button" class="close" data-dismiss="modal" aria-label="Close">
		    		<span aria-hidden="true">&times;</span>
				</button>
		  	</div>
		  	<div class="modal-body">
		    	<div class="row">
					<div class="col-md-12">
						<h2><?php echo $title; ?></h2>
					</div>
					<div class="col-md-12">
						<?php echo $content; ?>
					</div>
		      	</div>	
			</div>
		</div>
	</div>
</div>


<?php
$page_data = get_page_by_path('full-disclosure');

//store page title and content in variables
$title = $page_data->post_title; 
$content = apply_filters('the_content', $page_data->post_content);
?>
<div id="disclosure-modal" class="modal fade" tabindex="-1" role="dialog">
	<div class="modal-dialog modal-lg" role="document">
		<div class="modal-content">
		    <div class="modal-header">
		    	<button type="button" class="close" data-dismiss="modal" aria-label="Close">
		    		<span aria-hidden="true">&times;</span>
				</button>
		  	</div>
		  	<div class="modal-body">
		    	<div class="row">
					<div class="col-md-12">
						<h2><?php echo $title; ?></h2>
					</div>
					<div class="col-md-12">
						<?php echo $content; ?>
					</div>
		      	</div>	
			</div>
		</div>
	</div>
</div>


<?php
$page_data = get_page_by_path('privacy-policy');

//store page title and content in variables
$title = $page_data->post_title; 
$content = apply_filters('the_content', $page_data->post_content);
?>
<div id="privacy-modal" class="modal fade" tabindex="-1" role="dialog">
	<div class="modal-dialog modal-lg" role="document">
		<div class="modal-content">
		    <div class="modal-header">
		    	<button type="button" class="close" data-dismiss="modal" aria-label="Close">
		    		<span aria-hidden="true">&times;</span>
				</button>
		  	</div>
		  	<div class="modal-body">
		    	<div class="row">
					<div class="col-md-12">
						<h2><?php echo $title; ?></h2>
					</div>
					<div class="col-md-12">
						<?php echo $content; ?>
					</div>
		      	</div>	
			</div>
		</div>
	</div>
</div>


<?php
$page_data = get_page_by_path('file-a-complaint');

//store page title and content in variables
$title = $page_data->post_title; 
$content = apply_filters('the_content', $page_data->post_content);
?>
<div id="complaint-modal" class="modal fade" tabindex="-1" role="dialog">
	<div class="modal-dialog modal-lg" role="document">
		<div class="modal-content">
		    <div class="modal-header">
		    	<button type="button" class="close" data-dismiss="modal" aria-label="Close">
		    		<span aria-hidden="true">&times;</span>
				</button>
		  	</div>
		  	<div class="modal-body">
		    	<div class="row">
					<div class="col-md-12">
						<h2><?php echo $title; ?></h2>
					</div>
					<div class="col-md-12">
						<?php echo $content; ?>
					</div>
		      	</div>	
			</div>
		</div>
	</div>
</div>

<?php
$page_data = get_page_by_path('contacts');

//store page title and content in variables
$title = $page_data->post_title; 
$content = apply_filters('the_content', $page_data->post_content);
?>
<div id="contact-modal" class="modal fade" tabindex="-1" role="dialog">
	<div class="modal-dialog modal-lg" role="document">
		<div class="modal-content">
		    <div class="modal-header">
		    	<button type="button" class="close" data-dismiss="modal" aria-label="Close">
		    		<span aria-hidden="true">&times;</span>
				</button>
		  	</div>
		  	<div class="modal-body">
		    	<div class="row">
					<div class="col-md-12">
						<h2><?php echo $title; ?></h2>
					</div>
					<div class="col-md-12">
						<?php echo $content; ?>
					</div>
		      	</div>	
			</div>
		</div>
	</div>
</div>

<script>
jQuery(document).ready(function( $ ) {	
	$('<div class="social-icons">' + $(".site-header .social-icons").html() + '</div>').insertBefore(".site-header ul#menu-primary-menu");
});
</script>
  <script type="text/javascript">
    window.heap=window.heap||[],heap.load=function(e,t){window.heap.appid=e,window.heap.config=t=t||{};var r=t.forceSSL||"https:"===document.location.protocol,a=document.createElement("script");a.type="text/javascript",a.async=!0,a.src=(r?"https:":"http:")+"//cdn.heapanalytics.com/js/heap-"+e+".js";var n=document.getElementsByTagName("script")[0];n.parentNode.insertBefore(a,n);for(var o=function(e){return function(){heap.push([e].concat(Array.prototype.slice.call(arguments,0)))}},p=["addEventProperties","addUserProperties","clearEventProperties","identify","removeEventProperty","setEventProperties","track","unsetEventProperty"],c=0;c<p.length;c++)heap[p[c]]=o(p[c])};
    heap.load("4070299172");
  </script>


